---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggmap)
setwd("C:/Users/Xiaojie Wei/Desktop/Fall 2018/GR5243 Applied Data Science/Project 2")
```

## Process Raw Data
```{r}
hospital <- read.csv("data/Hospital General Information.csv")
iips_data <- read.csv("data/Inpatient_Prospective_Payment_System__IPPS__Provider_Summary_for_the_Top_100_Diagnosis-Related_Groups__DRG__-_FY2011.csv")
#transform the address into latitude and longtitude
latlng <- read.csv("data/laglng_transform.csv")

save(iips_data,file = "output/iips_data.RData")
```

```{r}
colnames(iips_data)[colnames(iips_data)=="Provider.Id"] <- "Provider.ID"

# add latitude and longtitude data in hospital data
hospital$latitude <- latlng[,1]
hospital$longtitude <- latlng[,2]

```

```{r}
# unique(hospital$Efficient.use.of.medical.imaging.national.comparison)
# Turn "Not Available" into NA, "Above Average" into 3, "Average" into 2 and "Below Average" into 1.
levels(hospital$Efficient.use.of.medical.imaging.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Timeliness.of.care.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Effectiveness.of.care.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Patient.experience.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Readmission.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Safety.of.care.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Mortality.national.comparison) <- c(3, 1, NA, 2)
levels(hospital$Hospital.overall.rating) <- c(1, 2, 3, 4, 5, NA)
```

```{r}
hospital <- hospital[,c(-14,-16,-18,-20,-22,-24,-26,-28)]
```

## Delete latitude/longitude NA rows and error rows as it cannot be visualized on the map
```{r}
hos <- hospital[is.na(hospital$latitude) == F & is.na(hospital$longtitude) == F,]
save(hos,file = "output/hos.RData")
write.csv(hos,file = "output/hos.csv")

```


```{}
# subtract address information and delete the rows with the same content
iips_add <- iips_data[,c(2,3,4,5,6,7)]
iips_add <- iips_add[!duplicated(iips_add$Provider.ID), ]
save(iips_add,file = "output/iips_add.RData")
```


```{}
hospital.geo =
  iips_add[1:1700,] %>%
  select(Provider.Street.Address, Provider.City, Provider.State) %>%
  mutate(ADDRESS_Ext = paste(Provider.Street.Address, Provider.City, Provider.State, sep=",")) %>%
  mutate_geocode(ADDRESS_Ext)
```


## Merge hospital data into iips_datda dataset
```{r}
iips_data <- iips_data %>%
  merge(hos, by = "Provider.ID",all=TRUE) 

# during the merge process, delete the missing value(NA) of variabel (Hospital.Name)
iips1 <- iips_data[is.na(iips_data$Hospital.Name) == F,]

write.csv(iips_data,file = "output/iips.csv")
write.csv(iips1,file = "output/iips1.csv")

save(iips_data,file = "output/iips.RData")
save(iips1,file = "output/iips1.RData")
load(iips,file="output/iips.RData")
```


